### ISSUE TITLE
Musicbotが再生途中に切断される問題

### ISSUE THREAD

**Issue by supleiades** [mo9mo9study/discord.study#10]
このエラーから問題を発見するところから開始
```
Task exception was never retrieved
future: <Task finished coro=<MusicPlayer._play() done, defined at /home/ec2-user/repos/musicbot2/MusicBot/musicbot/player.py:259> exception=ClientException('Not connected to voice.')>
Traceback (most recent call last):
  File "/home/ec2-user/repos/musicbot2/MusicBot/musicbot/player.py", line 307, in _play
    self.voice_client.play(self._source, after=self._playback_finished)
  File "/usr/local/lib/python3.7/site-packages/discord/voice_client.py", line 363, in play
    raise ClientException('Not connected to voice.')
discord.errors.ClientException: Not connected to voice.
```

**Comment by supleiades** [comment]
対象のリポジトリ
https://github.com/Just-Some-Bots/MusicBot.git

**Comment by supleiades** [comment]
このissueにて修正待ち
https://github.com/Just-Some-Bots/MusicBot/issues/2047

**Comment by supleiades** [comment]
自前で動かすmusicbotではなく、他社のBOT機能を利用するようにしたためクローズ
