### ISSUE TITLE
タグ付機能周辺のエラー？

### ISSUE THREAD

**Issue by supleiades** [mo9mo9study/discord.study#81]
とりあえず記録としてissueにメモ
```
Ignoring exception in on_reaction_add
Traceback (most recent call last):
  File "/home/ec2-user/.anyenv/envs/pyenv/versions/3.8.2/lib/python3.8/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "post_week_result.py", line 473, in on_reaction_add
    # リアクションが勉強アイテ に対応するものかを判定する
  File "/home/ec2-user/.anyenv/envs/pyenv/versions/3.8.2/lib/python3.8/site-packages/emoji/core.py", line 82, in demojize
    return re.sub(u'\ufe0f','',(get_emoji_regexp().sub(replace, string)))
TypeError: expected string or bytes-like object
```
これが大量に出力されていた

**Comment by nntsugu** [comment]
# 原因
- botメッセージへのリアクションにカスタム絵文字が指定された場合、emojiパッケージが対応していないためエラーが出る
# 修正方針
- emojiパッケージを使用する前にカスタム絵文字かどうかを判定するガード節を用意する
- ^はstudy_targetに必要な機能なのでそちらに実装する
- post_weekly_resutlには必要ない機能なので排除する

**Comment by nntsugu** [comment]
PR: https://github.com/mo9mo9study/discord.study/pull/82
